name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  release-linux:
    #if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build Default
        run: cargo build --all --release && strip target/release/interpreter && mv target/release/interpreter target/release/interpreter_amd64

      - name: Build NoDefault
        run: cargo build --all --release --no-default-features && strip target/release/interpreter && mv target/release/interpreter target/release/interpreter_small_amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/interpreter_amd64
            target/release/interpreter_small_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
